//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test22
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тест.
    /// </summary>
    // *** Start programmer edit section *** (тест CustomAttributes)

    // *** End programmer edit section *** (тест CustomAttributes)
    [AutoAltered()]
    [Caption("Тест")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("тестE", new string[] {
            "цена as \'Цена\'",
            "ном as \'ном\'",
            "ном.номном as \'номном\'",
            "ном.контр.контраг as \'контраг\'"})]
    [View("тестL", new string[] {
            "цена as \'Цена\'"})]
    public class тест : ICSSoft.STORMNET.DataObject
    {
        
        private int fцена;
        
        private IIS.Test22.ном fном;
        
        // *** Start programmer edit section *** (тест CustomMembers)

        // *** End programmer edit section *** (тест CustomMembers)

        
        /// <summary>
        /// цена.
        /// </summary>
        // *** Start programmer edit section *** (тест.цена CustomAttributes)

        // *** End programmer edit section *** (тест.цена CustomAttributes)
        public virtual int цена
        {
            get
            {
                // *** Start programmer edit section *** (тест.цена Get start)

                // *** End programmer edit section *** (тест.цена Get start)
                int result = this.fцена;
                // *** Start programmer edit section *** (тест.цена Get end)

                // *** End programmer edit section *** (тест.цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (тест.цена Set start)

                // *** End programmer edit section *** (тест.цена Set start)
                this.fцена = value;
                // *** Start programmer edit section *** (тест.цена Set end)

                // *** End programmer edit section *** (тест.цена Set end)
            }
        }
        
        /// <summary>
        /// Тест.
        /// </summary>
        // *** Start programmer edit section *** (тест.ном CustomAttributes)

        // *** End programmer edit section *** (тест.ном CustomAttributes)
        [PropertyStorage(new string[] {
                "ном"})]
        [NotNull()]
        public virtual IIS.Test22.ном ном
        {
            get
            {
                // *** Start programmer edit section *** (тест.ном Get start)

                // *** End programmer edit section *** (тест.ном Get start)
                IIS.Test22.ном result = this.fном;
                // *** Start programmer edit section *** (тест.ном Get end)

                // *** End programmer edit section *** (тест.ном Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (тест.ном Set start)

                // *** End programmer edit section *** (тест.ном Set start)
                this.fном = value;
                // *** Start programmer edit section *** (тест.ном Set end)

                // *** End programmer edit section *** (тест.ном Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "тестE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View тестE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("тестE", typeof(IIS.Test22.тест));
                }
            }
            
            /// <summary>
            /// "тестL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View тестL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("тестL", typeof(IIS.Test22.тест));
                }
            }
        }
    }
}
